/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package major_project;

import javafx.application.Application;
import javafx.stage.Stage;
import major_project.model.AppEngine;
import major_project.model.DB.Database;
import major_project.view.AppWindow;

public class Main extends Application {
    private static boolean runInputDummy = false;
    private static boolean runOutputDummy = false;
    private final AppEngine model = new AppEngine();
    private final AppWindow view = new AppWindow(model);


    public static void main(String[] args) {
        try {
            if (args[0].equals("offline")) {
                runInputDummy = true;
            }

            if (args[1].equals("offline")) {
                runOutputDummy = true;
            }
        } catch (Exception e) {
            // do nothing
        }
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        model.setInputDummy(runInputDummy);
        model.setOutputDummy(runOutputDummy);
        model.getDbHelper().cerateDB();
        model.getDbHelper().setupDB();
        primaryStage.setScene(view.getScene());
        primaryStage.setTitle("Major Project");


        primaryStage.show();

    }

    /*
    Caching:
https://jenkov.com/tutorials/javafx/tableview.html fix table cells
https://www.youtube.com/watch?v=gdef6jSRF2g&ab_channel=CoolITHelp

     */
}


