/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package major_project;

import major_project.model.AppEngine;
import major_project.view.AppWindow;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ConstructorTests {
    public AppEngine model;

    @BeforeEach
    public void init() {
        this.model = new AppEngine();
    }

    @Test
    public void testGetAPIkey() {
        String API_KEY = model.getInputAPIkey();
        assertEquals(API_KEY, System.getenv("INPUT_API_KEY"));
    }

    @Test
    public void testGetAPIid() {
        String API_KEY = model.getInputAPIid();
        assertEquals(API_KEY, System.getenv("INPUT_API_APP_ID"));
    }

    @Test
    public void testListsNotNull() {
        assertNotNull(model.getTotalAddedFood());
        assertNotNull(model.getRunningTotal());
        assertNotNull(model.getSetMaxes());
    }
}
